module.exports = {
    User:           require('./user'),
    Transaction:    require('./transaction'),
    Tag:            require('./tag'),
    Auction:        require('./auction'),
    Guild:          require('./guild'),
    Promo:          require('./promo'),
    Hero:           require('./hero'),
    Cardinfo:       require('./cardinfo'),
    Audit:          require('./audit'),
    AuditAucSell:   require('./auditAucSell'),
    AuditTags:      require('./auditTag'),
    Plots:          require('./plot'),
    UserCard:       require('./userCard'),
    UserEffect:     require('./userEffect'),
    UserInventory:  require('./userInventory'),
    UserStats:      require('./userstats'),
    UserSlot:       require('./userSlot'),
    UserQuest:      require('./userQuest'),
    Kofi:           require('./kofi'),
    GuildBuilding:  require('./guildBuilding'),
    GuildUser:      require('./guildUser'),
}
