const {model, Schema} = require('mongoose')

module.exports = model('Userstats', {
    discord_id:     { type: String, index: true },
    username:       { type: String },
    daily:          { type: Date, index: true },
    claims:         { type: Number, default: 0 },
    promoclaims:    { type: Number, default: 0 },
    totalregclaims: { type: Number, default: 0 },
    aucsell:        { type: Number, default: 0 },
    aucbid:         { type: Number, default: 0 },
    aucwin:         { type: Number, default: 0 },
    liquefy:        { type: Number, default: 0 },
    liquefy1:       { type: Number, default: 0 },
    liquefy2:       { type: Number, default: 0 },
    liquefy3:       { type: Number, default: 0 },
    draw:           { type: Number, default: 0 },
    draw1:          { type: Number, default: 0 },
    draw2:          { type: Number, default: 0 },
    draw3:          { type: Number, default: 0 },
    forge:          { type: Number, default: 0 },
    forge1:         { type: Number, default: 0 },
    forge2:         { type: Number, default: 0 },
    forge3:         { type: Number, default: 0 },
    tags:           { type: Number, default: 0 },
    rates:          { type: Number, default: 0 },
    wish:           { type: Number, default: 0 },
    usersell:       { type: Number, default: 0 },
    botsell:        { type: Number, default: 0 },
    userbuy:        { type: Number, default: 0 },
    tomatoin:       { type: Number, default: 0 },
    tomatoout:      { type: Number, default: 0 },
    promoin:        { type: Number, default: 0 },
    promoout:       { type: Number, default: 0 },
    vialin:         { type: Number, default: 0 },
    vialout:        { type: Number, default: 0 },
    lemonin:        { type: Number, default: 0 },
    lemonout:       { type: Number, default: 0 },
    store:          { type: Number, default: 0 },
    store1:         { type: Number, default: 0 },
    store2:         { type: Number, default: 0 },
    store3:         { type: Number, default: 0 },
    store4:         { type: Number, default: 0 },
    t1quests:       { type: Number, default: 0 },
    t2quests:       { type: Number, default: 0 },
})
