module.exports = {
    user: require('./user'),
    hero: require('./hero'),
    card: require('./card'),
    eval: require('./eval'),
    tag: require('./tag'),
    guild: require('./guild'),
    auction: require('./auction'),
    effect: require('./effect'),
    collection: require('./collection'),
    transaction: require('./transaction'),
    audit: require('./audit'),
    meta: require('./meta'),
    webhooks: require('./webhooks'),
    preferences: require('./preferences'),
    plot: require('./plot'),
    expedition: require('./expedition'),
    battle: require('./battle'),
}
